version: '3'
services:
  datn-mysql:
    image: mysql:8.0.25
    container_name: datn-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="" --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ABC123456
      MYSQL_DATABASE: datn
      MYSQL_USER: nghiapd
      MYSQL_PASSWORD: ABC123456
      LANG: C.UTF-8
    ports:
      - 13306:3306

  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abc123456
      POSTGRES_DB: datn

  datn-redis:
    image: 'redis:6-alpine'
    container_name: datn-redis
    ports:
      - 16379:6379
